sudo: false

language: php

php:
  - 5.5
  - 7.0

env:
  global:
    - SYMFONY_DEPRECATIONS_HELPER=weak
  matrix:
    - SULU_ORM=mysql SULU_PHPCR=jackrabbit
#    - SULU_ORM=postgres SULU_PHPCR=jackrabbit
#    - SULU_ORM=mysql SULU_PHPCR=doctrine_dbal
#    - SULU_ORM=postgres SULU_PHPCR=doctrine_dbal

before_script:
  - composer self-update
  - composer install
  - ./bin/jackrabbit.sh

script: 
  - time ./bin/runtests.sh -i -a
  - phpunit

notifications:
  slack:
    secure: "Gd3/1e0pBKvJv1UhWpBkWijJpmSWlarg6uPBJO0h4z1IpkZjd++jOjhmOQ7n+yMfuapQuJTcVOK0yIWu7orJoGAKFkBlMEIrLk1xMAG9phjjMLUO0FWgcQ3eVW5mTyfMBtClz4OL5wXckw17ohtXHDK8qnI0Hz9Qj8Rqgf2OZhM="

