sulu_contact.customer:
    type: rest
    resource: Sulu\Bundle\ContactBundle\Controller\CustomerController

sulu_contact.contacts:
    type: rest
    resource: Sulu\Bundle\ContactBundle\Controller\ContactController

sulu_contact.countries:
    type: rest
    resource: Sulu\Bundle\ContactBundle\Controller\CountryController

sulu_contact.accounts:
    type: rest
    resource: Sulu\Bundle\ContactBundle\Controller\AccountController

sulu_contact.contacttitle:
    type: rest
    resource: Sulu\Bundle\ContactBundle\Controller\ContactTitleController

sulu_contact.contactposition:
    type: rest
    resource: Sulu\Bundle\ContactBundle\Controller\PositionController

sulu_contact.account_medias:
    type: rest
    parent: sulu_contact.accounts
    resource: Sulu\Bundle\ContactBundle\Controller\AccountMediaController

sulu_contact.contact_medias:
    type: rest
    parent: sulu_contact.contacts
    resource: Sulu\Bundle\ContactBundle\Controller\ContactMediaController
